language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk11
  - openjdk11

addons:
  sonarcloud:
    organization: "qdgtruie-github" # the key of the org you chose at step #3
    token:
      secure: "ff142467de49bc44b68575cac253b8bde6b9f1f1"  # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - ./gradlew clean test --info
  - sonar-scanner

jobs:
  include:
    - stage: deploy
      name: "build docker image"
      script:
        - docker build -t tondeuse_test .
        - docker images
        - docker tag SNAPSHOT


