language: java

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk11
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "qdgtruie-github" # the key of the org you chose at step #3

script:
  # other script steps might be done before running the actual analysis
  - ./gradlew clean test --info
  - sonar-scanner -Dsonar.verbose=true -X

jobs:
  include:
    - stage: deploy
      name: "build docker image"
      #if: env($DOCKER_USER) IS present AND env($DOCKER_PASSWORD) IS present
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker build -t tondeuse_test:$COMMIT .
        - docker images
        - docker tag tondeuse_test:$COMMIT $DOCKER_USER/tondeuse
        - docker push $DOCKER_USER/tondeuse
        #- docker run --rm $DOCKER_USER/tondeuse


