/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.publicissapient.tondeuse;

import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {

    }

}
