/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.publicissapient.tondeuse;


import org.junit.jupiter.api.Test;

public class ConsoleAppTest {
    @Test
    public void testAppHasAGreeting() {

    }

}
