/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.publicissapient.tondeuse;

import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Report;
import net.jqwik.api.Reporting;
import net.jqwik.api.constraints.WithNull;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;


class ConsoleAppTest {

    @Property(tries=10) @Report(Reporting.GENERATED)
    void AnyArgCanBePassed(@ForAll @WithNull final String[] args){
        assertDoesNotThrow(()->ConsoleApp.main(args));
    }

}
