/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.publicissapient.tondeuse;

import com.publicissapient.tondeuse.domain.Configuration.Configuration;
import com.publicissapient.tondeuse.domain.Configuration.ConfigurationException;
import com.publicissapient.tondeuse.domain.Configuration.Providers.FileConfigurationProvider;
import com.publicissapient.tondeuse.domain.MownerController;

public class App {

    private static final String FILE_CONF = "file.txt";

    private void run()  throws ConfigurationException {

        new MownerController().load(Configuration.basedOn(new FileConfigurationProvider(FILE_CONF))).Run();
    }

    public static void main(String[] args) throws ConfigurationException {
        new App().run();
    }


}
