/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.publicissapient.tondeuse;

import com.publicissapient.tondeuse.domain.PositionProvider;
import com.publicissapient.tondeuse.domain.configuration.Configuration;
import com.publicissapient.tondeuse.domain.configuration.errors.ConfigurationException;
import com.publicissapient.tondeuse.domain.configuration.errors.InvalidMoveEventArg;
import com.publicissapient.tondeuse.domain.configuration.providers.FileConfigurationProvider;
import com.publicissapient.tondeuse.service.MownerController;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ConsoleApp {

    private static final String FILE_CONF = "file.txt";

    private void run()  throws ConfigurationException {

        log.info("[ConsoleApp] Starting mowner controller...");
        new MownerController()
                .load(Configuration.basedOn(FileConfigurationProvider.fromFileResource(FILE_CONF)))
                .withAlerter(ConsoleApp::notifyInvalidMove)
                .withResultPublisher(ConsoleApp::printMownerFinalLocation)
                .run();
    }

    public static void main(String[] args) throws ConfigurationException {
        new ConsoleApp().run();
    }

    private static void notifyInvalidMove(InvalidMoveEventArg x) {
        if (log.isInfoEnabled())
            log.info("[Mowner {} ] tried to reach invalid position at {}",
                    x.getMownerID().toString(), x.getTargetPosition().toString());
    }

    private static void printMownerFinalLocation(PositionProvider x) {
        if (log.isInfoEnabled())
            log.info("[Mowner {} ] Job complete : position is {}",
                    x.getId().toString(), x.getCurrentLocation().toString());
    }

}
